export * from './Onboarding/Onboarding';
export * from './Login/Login';
export * from './Signup/Signup';
export * from './Home/Home';
export * from './VerifyOtp';
export * from './Orders';
export * from './Location';
export * from './Cart';
export * from './Profile';