export const AUTH = {
  ONBOARDING: 'Onboarding',
  LOGIN: 'Login',
  SIGNUP: 'Signup',
  FORGOT_PASSWORD: 'ForgotPassword',
  NEW_PASSWORD: 'NewPassword',
  VERIFT_OTP: 'VerifyOtp',
  OTP_VERIFIED: 'OtpVerified',
} as const;

export const SCREENS = {
  MAIN_TABS: 'MainTabs',
  HOME: 'Home',
  MY_ORDERS: 'MyOrders',
  MY_LOCATION: 'MyLocation',
  CART: 'Cart',
  PROFILE: 'Profile',
  EDIT_PROFILE: 'EditProfile',
  CHANGE_PASSWORD: 'ChangePassword',
  CHANGE_EMAIL: 'ChangeEmail',
  VERIFT_OTP: 'VerifyOtp',
  OTP_VERIFIED: 'OtpVerified',
  EDITLISTING: 'EditListing',
  CREATE_SERVICE: 'CreateService',
  CREATE_PRODUCT: 'CreateProduct',
  CREATE_BUSINESS: 'CreateBusiness',
  LISTINGS: 'Listings',
  SETUP_PAYOUT: 'SetupPayout',
  ADD_SERVICE: 'AddService',
} as const;
